name: Master Merge 
on:
  check_run:
    types: [completed]

jobs:
  staging_merge:
    runs-on: ubuntu-latest
    steps:
    - name : GITHUB CONTEXT
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      